name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Stage 1: Preparation
  preparation:
    name: Preparation
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ steps.generate-run-id.outputs.run-id }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Run ID
        id: generate-run-id
        run: |
          RUN_ID=$(cat /proc/sys/kernel/random/uuid)
          echo "Preparation stage: RunID=${RUN_ID}"
          echo "Build Number: ${{ github.run_number }}"
          echo "RunID=${RUN_ID}" > prep.txt
          echo "run-id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Upload prep data artifact
        uses: actions/upload-artifact@v4
        with:
          name: prep-data
          path: prep.txt
          retention-days: 1

  # Stage 2: Run Jobs in Parallel
  run-jobs-parallel:
    name: Run Jobs in Parallel
    needs: preparation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [JobA, JobB, JobC]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download prep data
        uses: actions/download-artifact@v4
        with:
          name: prep-data

      - name: Run ${{ matrix.job }}
        run: |
          echo "${{ matrix.job }} running with $(cat prep.txt)" > ${{ matrix.job }}.log
          cat ${{ matrix.job }}.log

      - name: Mark job complete
        run: echo "${{ matrix.job }} complete"

      - name: Upload job results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job }}-data
          path: ${{ matrix.job }}.log
          retention-days: 1

  # Stage 3: Integration
  integration:
    name: Integration
    needs: run-jobs-parallel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JobA results
        uses: actions/download-artifact@v4
        with:
          name: JobA-data

      - name: Download JobB results
        uses: actions/download-artifact@v4
        with:
          name: JobB-data

      - name: Download JobC results
        uses: actions/download-artifact@v4
        with:
          name: JobC-data

      - name: Integrate job results
        run: |
          cat JobA.log JobB.log JobC.log > combined.txt
          echo "Integration complete"

      - name: Upload combined results
        uses: actions/upload-artifact@v4
        with:
          name: integration-data
          path: combined.txt
          retention-days: 1

  # Stage 4: Deploy
  deploy:
    name: Deploy
    needs: integration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download integration results
        uses: actions/download-artifact@v4
        with:
          name: integration-data

      - name: Deploy step
        run: |
          echo "Deploy step using combined results:"
          cat combined.txt
